// vue-example/src/App.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import getAutoCompleteResults from "./getAutoCompleteResults";

const filter = ref('');
const debouncedFilter = ref('');
const loading = ref(false);
const error = ref('');
const suggestions = ref<string[]>([]);
let abortController: AbortController | null = null;

async function getSuggestions(debouncedFilter: string) {
  loading.value = false;
  error.value = '';
  suggestions.value = [];
  if (!abortController) return;
  if (!filter) {
    return;
  }
  loading.value = true;
  try {
    const results = await getAutoCompleteResults(debouncedFilter, abortController.signal)
    suggestions.value = results;
    loading.value = false;
  } catch (e) {
    const err = e as Error;
    if (err.name !== "AbortError") {
      error.value = err.message;
      loading.value = false;
    }
  }
}

let timeout = -1;
watch(filter, () => {
  clearTimeout(timeout);
  timeout = setTimeout(() => {
    if (abortController) {
      abortController.abort();
    }
    abortController = new AbortController();
    debouncedFilter.value = filter.value;
    getSuggestions(filter.value)
  }, 300);
});
</script>

<template>
  <main class="container">
    <form @submit.prevent="">
      <label>
        Tree
        <input v-model="filter" />
      </label>
    </form>
    <progress v-if="loading" />
    <article v-if="error" style="background: #e53935; color: white">
      {{ error }}
    </article>
    <article v-for="suggestion in suggestions" :key="suggestion">{{ suggestion }}</article>
    <p v-if="!debouncedFilter">Type to see suggestions.</p>
    <p v-if="!error && debouncedFilter && suggestions.length === 0 && !loading">No suggestions to display.</p>
  </main>
</template>

// svelte-example/src/App.svelte
<script lang="ts">
  import getAutoCompleteResults from "./getAutoCompleteResults";

  let debouncedFilter = '';
  let loading = false;
  let error = '';
  let suggestions: string[] = [];

  let abortController = null;

  async function getSuggestions(filter) {
    loading = false;
    error = '';
    suggestions = [];
    if (!filter) {
      return;
    }
    loading = true;
    try {
      const results = await getAutoCompleteResults(filter, abortController.signal)
      suggestions = results;
      loading = false;
    } catch (e) {
      const err = e as Error;
      if (err.name !== "AbortError") {
        error = err.message;
        loading = false;
      }
    }
  }

  $: getSuggestions(debouncedFilter);

  let timeout = -1;
  function setDebouncedFilter(event) {
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      if (abortController) {
        abortController.abort();
      }
      abortController = new AbortController();
      debouncedFilter = event.target.value;
    }, 300);
  } 
</script>

<main class="container">
  <form on:submit|preventDefault={() => {}}>
    <label>
      Tree
      <input on:input={setDebouncedFilter} />
    </label>
  </form>
  {#if loading}
    <progress />
  {/if}
  {#if error}
    <article style="background: #e53935; color: white">
      {error}
    </article>
  {/if}
  {#each suggestions as suggestion}
    <article>{suggestion}</article>
  {/each}
  {#if !debouncedFilter}
    <p>Type to see suggestions.</p>
  {/if}
  {#if !error && debouncedFilter && suggestions.length === 0 && !loading}
    <p>No suggestions to display.</p>
  {/if}
</main>
