// solid-example/src/App.tsx
import { Accessor, Component, onCleanup } from 'solid-js';
import { createSignal, createEffect, createResource } from 'solid-js';
import getAutoCompleteResults from "./getAutoCompleteResults";

function useDebouncedValue(value: Accessor<string>) {
  const [debouncedValue, setDebouncedValue] = createSignal(value());
  const [abortController, setAbortController] = createSignal(new AbortController());

  createEffect(() => {
    if (!value()) {
      setDebouncedValue("");
      return;
    }
    const timeoutId = setTimeout(() => {
      setAbortController(new AbortController());
      setDebouncedValue(value());
    }, 300);
    onCleanup(() => {
      abortController().abort();
      clearTimeout(timeoutId);
    });
  });

  return { debouncedValue, abortController };
}

const App: Component = () => {
  const [filter, setFilter] = createSignal("");
  const { debouncedValue, abortController } = useDebouncedValue(filter);
  const [suggest] = createResource(debouncedValue, (value) => getAutoCompleteResults(
    value,
    abortController().signal
  ))

  return (
    <section class="container">
      <form onSubmit={(e) => e.preventDefault()}>
        <label>
          Tree
          <input onInput={(e) => {
            setFilter(e.target.value);
          }} value={filter()} />
        </label>
      </form>
      {suggest.loading && <progress />}
      {suggest.error && (
        <article style={{ background: "#e53935", color: "white" }}>
          {suggest.error.message}
        </article>
      )}
      <section>
        {!suggest.loading && suggest()?.map((suggestion) => (
          <article>{suggestion}</article>
        ))}
        {!debouncedValue() && <p>Type to see suggestions.</p>}
        {!suggest.error && debouncedValue() && !suggest()?.length && !suggest.loading && (
          <p>No suggestions to display.</p>
        )}
      </section>
    </section>
  );
};

export default App;

// react-example/src/App.tsx
import { useEffect, useState } from "react";
import getAutoCompleteResults from "./getAutoCompleteResults";

function useDebouncedValue(value: string) {
  const [debouncedValue, setDebouncedValue] = useState(value);

  useEffect(() => {
    if (!value) {
      setDebouncedValue("");
      return;
    }
    const timeoutId = setTimeout(() => {
      setDebouncedValue(value);
    }, 300);
    return () => {
      clearTimeout(timeoutId);
    };
  }, [value]);

  return debouncedValue;
}

function App() {
  const [filter, setFilter] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const debouncedValue = useDebouncedValue(filter);

  useEffect(() => {
    const abortController = new AbortController();
    (async () => {
      setSuggestions([]);
      setError("");
      setLoading(false);
      if (!debouncedValue) return;
      setLoading(true);
      try {
        const results = await getAutoCompleteResults(
          debouncedValue,
          abortController.signal
        );
        setSuggestions(results);
        setLoading(false);
      } catch (e) {
        const error = e as Error;
        if (error.name !== "AbortError") {
          setError(error.message);
          setLoading(false);
        }
      }
    })();

    return () => {
      abortController.abort();
    };
  }, [debouncedValue]);

  return (
    <section className="container">
      <form onSubmit={(e) => e.preventDefault()}>
        <label>
          Tree
          <input onChange={(e) => setFilter(e.target.value)} value={filter} />
        </label>
      </form>
      {loading && <progress />}
      {error && (
        <article style={{ background: "#e53935", color: "white" }}>
          {error}
        </article>
      )}
      <section>
        {suggestions.map((suggestion) => (
          <article key={suggestion}>{suggestion}</article>
        ))}
        {!debouncedValue && <p>Type to see suggestions.</p>}
        {!error && debouncedValue && suggestions.length === 0 && !loading && (
          <p>No suggestions to display.</p>
        )}
      </section>
    </section>
  );
}

export default App;
